import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Toaster } from "sonner";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Professional Next.js Stack",
  description: "Generated by Next.js Stack CLI",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="antialiased">
        <ReduxProvider>
          <ReactQueryProvider>
            {children}
            <Toaster richColors position="top-center" />
          </ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
